### ISSUE TITLE
Webkit / Chromium compatibility

### ISSUE THREAD

**Issue by kao98** [Mialus/Clueless-Life#2]
Known compatibility issues exists with the audio engine on WebKit / Chromium.
It results in audio glitch, and gameplay issue (ie. impossibility to pick up the baby bottle).

It seems this is because of the "onended" event not fired by webkit and chromium.

**Comment by fdadeau** [comment]
However, it seems that the issue has been solved in not-so-recent versions of these browsers. 
Could it be a small bug in audio.js? ;-)

**Comment by kao98** [comment]
Actually, no. The problem is because of the use of "addEventListener".
I've just tested right now replacing "source.addEventListener('ended', (...))" with "source.onended = (...)", and that fixed the problem.

For example, gamejam.js, line 722, the following snippet fix the issue with the baby bottle.
```
    biberon.onUseInScene = function() {
        game.audio.load("gamedata/sounds/bottle-out-microwave.mp3", function (buffer) {
            source = game.audio.play(buffer);
            source.onended = function () {
                game.addItemToInventory("biberon");      
            };
            /*source.addEventListener("ended", function () {
                game.addItemToInventory("biberon");                   
            });*/
        });
    }
```

**Comment by fdadeau** [comment]
OK. Nice. I'll update the repository and the website ;-)

**Comment by kao98** [comment]
I was about to report this, but too late :p : http://code.google.com/p/chromium/issues/detail?id=403908

**Comment by fdadeau** [comment]
Update done. 

However, there seems to be another issue with Safari's audio management. 

When the baby is babling (when in the inventory), it is impossible to exit the bedroom. It is related to an instruction that fails during the execution. 

audio.js:111 --> source.stop(0) doesn't seem to work which causes the execution to abort on Safari (works fine on FF & Chrome).

Temporarily solved using a try/catch block (not proud of it, but it now works)

**Comment by kao98** [comment]
This is weird.
But I guess the audio engine deserve to be rewrite a little bit. We should
create a branch dedicated to that.

Otherwise, what happens with the readme.md file? What did you wanted to do?
:-p

2015-01-28 15:37 GMT+01:00 fdadeau <notifications@github.com>:

**Comment by fdadeau** [comment]
I remove the last paragraph with the link to download the game (not necessary, as it works fine online).

There was a merge issue. It is now corrected.
